---
ID: "8d4f4bb1-e9a4-44ff-b9cb-f3f375cb89ac"
Parent: "58ccc50a-b886-41ef-a4b3-a5bf3d89b8a3"
Template: "58ccc50a-b886-41ef-a4b3-a5bf3d89b8a3"
Path: "/sitecore/templates/Project/alex-lee/Partial Design Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {58CCC50A-B886-41EF-A4B3-A5BF3D89B8A3}
    {FD2059FD-6043-4DFE-8C04-E2437CE87634}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "1794b25f-cdd4-42da-aca9-a8544ddd2e43"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260305T001605Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\andrew.vieau@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\andrew.vieau@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7815d4c6-ae20-4a40-aae6-2fee5ff56505"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\andrew.vieau@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260305T001610Z
