---
ID: "36b65d2a-1cb7-4528-a2df-fc1aa7bf0f41"
Parent: "91e27206-4f54-4c3d-ab74-2b6f2af8f107"
Template: "91e27206-4f54-4c3d-ab74-2b6f2af8f107"
Path: "/sitecore/templates/Project/industry-verticals/Rendering Parameters/Hall Rental Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "97530099-1a96-4c6e-a873-17bb5897dac4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\andrew.vieau@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260501T174259Z
